# Generated by Django 3.0.5 on 2020-05-04 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robinhood', '0002_currentvalue'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentvalue',
            name='date',
            field=models.DateField(default='2020-01-01'),
        ),
    ]
