# Generated by Django 3.0.5 on 2020-05-04 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robinhood', '0003_currentvalue_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentvalue',
            name='date',
            field=models.DateField(default='2020-01-01', unique=True),
        ),
    ]
