# Generated by Django 3.0.5 on 2020-05-09 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robinhood', '0004_auto_20200504_0532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentvalue',
            name='date',
            field=models.DateField(default='2020-01-01'),
        ),
    ]
